language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
    - python setup.py develop
script:
    - cd tests/
    - py.test --cov cpe --doctest-modules .
    - cd ../docs/
    - sphinx-build -W -b html -d /tmp/doctrees . /tmp/html
after_success:
    - coveralls
